name: udacity-dynamic-risk-assessment-system
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flask
  - requests
  - pandas
  - numpy
  - scikit-learn
  - pyarrow
  - matplotlib
  - seaborn